# Generated by Django 2.2.2 on 2019-06-24 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0003_faculty_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculties_of_university', to='universities.University'),
        ),
    ]
