# Generated by Django 2.2.2 on 2019-06-19 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abiturs', '0001_initial'),
        ('universities', '0002_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assigned', models.DateField()),
                ('abitur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abiturs.Abitur')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universities.Faculty')),
            ],
        ),
    ]
