# Generated by Django 2.2.2 on 2019-06-25 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('abitur', 'faculty'), name='abitur_unique'),
        ),
    ]
