# Generated by Django 2.2.2 on 2019-06-25 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20190625_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
